### ISSUE TITLE
Pages that still need to be designed

### ISSUE THREAD

**Issue by bboulesteix** [BasileM/rails-hiry#91]
* [ ] housing#show (#90) => page de présentation d’un bien
* [ ] rental#show (#93) => bail
* [ ] receipts#index (#94) => état des lieux
* [ ] inventory#index (#95) => quittances
